### ISSUE TITLE
部署问题咨询

### ISSUE THREAD

**Issue by Guwenqiang** [geekape/geek-navigation#30]
hi  你好，两个问题请教一下：
1、导入数据报错如下：
node reptile/index.js
/root/install/geek-navigation/reptile/index.js:48
async function main() {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

1、启动服务报错如下：
npm run serve

> geek-navigation@0.1.0 serve /root/install/geek-navigation
> vue-cli-service serve

/root/install/geek-navigation/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/install/geek-navigation/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)

npm ERR! Linux 3.10.0-957.21.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! geek-navigation@0.1.0 serve: `vue-cli-service serve`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the geek-navigation@0.1.0 serve script 'vue-cli-service serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the geek-navigation package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs geek-navigation
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls geek-navigation
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/install/geek-navigation/npm-debug.log

**Comment by geekape** [comment]
第2个是npm包问题，第一个语法错误，看是不是改动了什么

**Comment by Guwenqiang** [comment]
1、没有改动任何配置
2、npm是yum安装的，版本信息上面也有，版本导致的？

**Comment by linuxroc** [comment]
启动后台报错    (node:23002) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
app listening on port 3000.

**Comment by geekape** [comment]
mongoose连接mongodb,最新写法，后面要跟{ useNewUrlParser: true }

`
var db = mongoose.connect('mongodb://127.0.0.1:27017/navigation', { useNewUrlParser: true });
`

**Comment by taoook** [comment]
下载了zip包，怎么安装到服务器上，用哪个文件夹啊！
我想用动态版的
